# backend_app:
sudo: false

language: python

python:
  - 2.7
before_install: cd backend_app

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run -m unittest discover -s tests

after_success:
- codecov

# frontend_app:
#   language: node_js
#   node_js:
#     - 6
#   cache:
#     directories:
#       - node_modules
#   script:
#     - npm test
#     - npm run build